services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - backend_data:/app/data
    networks:
      - app-network
    restart: unless-stopped
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge