services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: backend:v2.0
    container_name: backend
    volumes:
      - backend_data:/app/data
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend:v2.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge